quiz = {
    "Command used to change ownership of files and directories.": "chown",
    "Remote access configuration file used to grant or deny access to users, groups, or everyone.": "/etc/security/access.conf",
    "A structure in a filesystem that identifies the location of file or directory on a block device and contains metadata about the file (except for the filename)": "inode",
    "System file that contains leap second details provided by the tzdata configuration": "/usr/share/zoneinfo/leap-seconds.list",
    "Software suite that is used to perform tasks involving authentication and authorization for applications": "PAM",
    "Legacy utility that allowing you to define a pool of network servers that are synchronized to a globally distributed network of time servers": "ntp",
    "Utility used to show network connections, routing tables, interface stats, and other network information": "netstat",
    "The location to view the apache2 log files in Debian/Ubuntu": "/var/log/apache2",
    "Flexible storage created from storage available on a volume group, similar to partitions on a physical disk": "logical volume",
    "Command to give a verbose display of the status of your system's firewall, listing all chains and displaying IP addresses rather than host names": "iptables -L -n -v",
    "Command to enable swap files or partitions": "swapon",
    "Command to disable swap files or partitions": "swapoff",
    "Legacy utility used to view all active network interfaces, including the loopback adapter": "ifconfig",
    "Command used to create a new group": "groupadd",
    "Legacy command that is used to display and manage information about the current routing table": "route",
    "File containing current information for any multiple-disk RAID configurations on the system.": "/proc/mdstat",
    "E-mail protocol where messages are stored and kept on the server": "IMAP",
    "Text file that provides a human friendly mapping between internet services and their assigned ports and protocol types": "/etc/services",
    "System resource limit set by the administrator, which cannot be changed by the user": "hard limit",
    "System resource limit set by the administrator which can be changed by the user up to the hard limit": "soft limit",
    "The primary configuration file for the BIND DNS server on Debian/Ubuntu systems": "/etc/bind/named.conf",
    "The configuration file for the updatedb command, used to manage the locate database(s)": "/etc/updatedb.conf",
}
